// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
const validateConfig = () => {
  const errors: string[] = [];
  
  if (!SUPABASE_URL) {
    errors.push('VITE_SUPABASE_URL is missing');
  } else if (!SUPABASE_URL.includes('supabase.co')) {
    errors.push('VITE_SUPABASE_URL is invalid - should be a Supabase URL');
  }
  
  if (!SUPABASE_PUBLISHABLE_KEY) {
    errors.push('VITE_SUPABASE_PUBLISHABLE_KEY is missing');
  }
  
  if (errors.length > 0) {
    console.error('❌ Supabase Configuration Errors:', errors);
    return false;
  }
  
  console.log('✅ Supabase Configuration Valid');
  return true;
};

const isConfigValid = validateConfig();

console.log('Supabase Config:', {
  url: SUPABASE_URL,
  keyExists: !!SUPABASE_PUBLISHABLE_KEY,
  isValid: isConfigValid,
});

// Create client only if config is valid
let supabase: any;

try {
  supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
  throw new Error('Supabase client initialization failed. Check your environment variables.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };